export default {
    "id": "pi_1DpeUP2eZvKYlo2CqDKio8pl",
    "object": "payment_intent",
    "amount": 1099,
    "amount_capturable": 0,
    "amount_received": 0,
    "application": null,
    "application_fee_amount": null,
    "automatic_payment_methods": null,
    "canceled_at": null,
    "cancellation_reason": null,
    "capture_method": "automatic",
    "charges": {
        "object": "list",
        "data": [],
        "has_more": false,
        "url": "/v1/charges?payment_intent=pi_1DpeUP2eZvKYlo2CqDKio8pl"
    },
    "client_secret": "pi_1DpeUP2eZvKYlo2CqDKio8pl_secret_3MeWaUVTnso5uc6N0eE04atp6",
    "confirmation_method": "automatic",
    "created": 1546792121,
    "currency": "eur",
    "customer": null,
    "description": null,
    "invoice": null,
    "last_payment_error": null,
    "livemode": false,
    "metadata": {},
    "next_action": null,
    "on_behalf_of": null,
    "payment_method": null,
    "payment_method_options": {},
    "payment_method_types": [
        "card"
    ],
    "processing": null,
    "receipt_email": 'stripe-webhook@test.com',
    "review": null,
    "setup_future_usage": null,
    "shipping": null,
    "statement_descriptor": null,
    "statement_descriptor_suffix": null,
    "status": "requires_payment_method",
    "transfer_data": null,
    "transfer_group": null
}