version: "3"
services:
  traefik:
    command:
      #- --log.level=DEBUG
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.graphql.address=:5433
    ports:
      - 8080:8080
      - 80:80
      - 5433:5433
  graphql:
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.http.services.graphql.loadbalancer.server.port=5433
      - traefik.http.routers.graphql.rule=Host(`localhost`)
      - traefik.http.routers.graphql.entrypoints=graphql
  db:
    container_name: smooms-db
    restart: always
    image: smooms-db
    build:
      context: ./db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5432:5432
  nextjs:
    container_name: nextjs
    restart: always
    build: .
    labels:
      - traefik.enable=true
      - traefik.http.services.nextjs.loadbalancer.server.port=3000
      - traefik.http.routers.nextjs.rule=Host(`localhost`)
      - traefik.http.routers.nextjs.entrypoints=web
volumes:
  db:
