version: "3"
services:
  traefik:
    image: traefik:v2.4
    container_name: traefik
    command:
      #- --log.level=DEBUG
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports:
      - 8080:8080
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  graphql:
    container_name: smooms-graphql
    restart: always
    image: smooms-graphql
    build:
      context: ./graphql
    env_file:
      - ./.env
    labels:
      - traefik.enable=true
      - traefik.http.services.my-app.loadbalancer.server.port=5433
