version: "3"
services:
  traefik:
    image: traefik:v2.4
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
  graphql:
    image: smooms-graphql
    build:
      context: ./graphql
    env_file:
      - ./.env
  ci:
    build: ./ci
