version: "3.3"
services:
  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  graphql:
    container_name: smooms-graphql
    restart: always
    image: smooms-graphql
    build:
      context: ./graphql
    env_file:
      - ./.env
    networks:
      - network
    ports:
      - 80:80
    labels:
      - "traefik.enable=true"

networks:
  network:

volumes:
  db:
