version: "3"
services:
  traefik:
    command:
      #- --log.level=DEBUG
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports:
      - 8080:8080
      - 80:80
  graphql:
    depends_on:
      - db
    labels:
      - traefik.enable=true
      - traefik.http.services.my-app.loadbalancer.server.port=5433
      - traefik.http.routers.my-app.rule=Host(`localhost`)
  db:
    container_name: smooms-db
    restart: always
    image: smooms-db
    build:
      context: ./db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5432:5432

volumes:
  db:
