version: "3"
services:
  traefik:
    command:
      #- --log.level=DEBUG
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.graphile.address=:5433
      - --certificatesresolvers.le.acme.email=urgent.programmer@gmail.com
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
    ports:
      - 443:443
      - 8080:8080
      - 80:80
      - 5433:5433
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
        awslogs-group: traefik
  graphql:
    labels:
      - traefik.enable=true
      - traefik.http.services.graphql.loadbalancer.server.port=5433
      - traefik.http.routers.graphql.rule=Host(`app.align.company`)
      - traefik.http.routers.graphql.tls.certresolver=le
      - traefik.http.routers.graphql.entrypoints=graphile
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
        awslogs-group: graphql
  nextjs:
    build: .
    labels:
      - traefik.enable=true
      - traefik.http.services.nextjs.loadbalancer.server.port=3000
      - traefik.http.routers.nextjs.rule=Host(`app.align.company`)
      - traefik.http.routers.nextjs.tls.certresolver=le
      - traefik.http.routers.nextjs.entrypoints=websecure
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-2
        awslogs-group: nextjs
