version: "3"
services:
  traefik:
    image: traefik:v2.4
    container_name: traefik
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
  graphql:
    container_name: smooms-graphql
    restart: always
    image: smooms-graphql
    build:
      context: ./graphql
    env_file:
      - ./.env
